### PR TITLE
Bump to latest resolve-package-path

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by stefanpenner** [comment]
@rwjblue ya strange, I haven't had a chance to debug yet...

**Comment by rwjblue** [comment]
Ran into a bug in the 1.1.1 -> 1.2.4 work, fixing over in https://github.com/stefanpenner/resolve-package-path/pull/17.

**Comment by stefanpenner** [comment]
oh github, why you close..

**Comment by stefanpenner** [comment]
@rwjblue resolve-package-path released, i'll update this PR

**Comment by stefanpenner** [comment]
updated, let's see what CI does...

@rwjblue thanks for debugging!

**Pull request merged**
